In [18]:
class Component():
    def __init__(self):
        self.CompCat = None
        self.Item = None
        self.Component = None
        self.EstimatedQuantity = None
        self.Unit = None
        self.EstimatedUnitCost = None
        self.EstimatedTotalCost = None
        self.YearLastDone = None
        self.FrequencyOrNormalServiceLife = None
        self.EstimatedRemainingUsefulLife = None
        self.NextYear = None
        self.ComponentAssessmentInCurrentDollars = None

Components = [] #empty array
DataStartsOnLine=22
f=open("Foxhall Components.txt", "r")

LineNum=0
for Line in f:
    LineNum += 1
    if LineNum >= DataStartsOnLine: #and LineNum <= DataStartsOnLine+3:
        # print(Line)
        tmp = Line.split(" ",1)
        Item = tmp[0]
        Rest = tmp[1]
        # print(Item)
        # print(Rest)
        if (Item.endswith("00")): 
            CompCat = Rest.replace('\n','')
            continue
        n = Rest.find("#")
        tmp = Rest.split("#",1)
        Comp = tmp[0]
        Rest = tmp[1]
        #print(Rest)
        tmp = Rest.split(" ",7)
        Qty = tmp[1]
        Unit = tmp[2]
        UnitCost = tmp[4]
        TotalCost = tmp[6]
        Rest = tmp[7]
        #print(Qty)
        #print(Unit)
        #print(UnitCost)
        #print(TotalCost)
        #print(Rest)
        tmp = Rest.split()
        Last=tmp[0]
        Freq=tmp[1]
        RemLife=tmp[2]
        Next=tmp[3]
        Assessment=tmp[5]
        Cmp = Component()
        Cmp.CompCat = CompCat
        Cmp.Item = Item
        Cmp.Component = Comp
        Cmp.EstimatedQuantity = Qty
        Cmp.Unit = Unit
        Cmp.EstimatedUnitCost = UnitCost
        Cmp.EstimatedTotalCost = TotalCost
        Cmp.YearLastDone = Last
        Cmp.FrequencyOrNormalServiceLife = Freq
        Cmp.EstimatedRemainingUsefulLife = RemLife
        Cmp.NextYear = Next
        Cmp.ComponentAssessmentInCurrentDollars = Assessment
        Components.append(Cmp)
ItemCount=len(Components)
print(ItemCount)
txt = '{},{},"{}","{}",{},"${}","${}",{},{},{},{},"${}"'
for n in range(ItemCount):
    print(txt.format(Components[n].CompCat, Components[n].Item, Components[n].Component, 
    Components[n].EstimatedQuantity, Components[n].Unit, Components[n].EstimatedUnitCost, 
    Components[n].EstimatedTotalCost, Components[n].YearLastDone, 
    Components[n].FrequencyOrNormalServiceLife, Components[n].EstimatedRemainingUsefulLife,
    Components[n].NextYear, Components[n].ComponentAssessmentInCurrentDollars))

181
Parking Garage,1.01,"Concrete repairs, B1 level","1",AL,"$50,000","$50,000",2011,12,5,2023,"$4,167"
Parking Garage,1.02,"Vehicle traffic coating B1 level, first time","23,000",SF,"$6.00","$138,000",-,one_time_project,5,2023,"$-"
Parking Garage,1.03,"Vehicle traffic coating, B1 level, recoat","23,000",SF,"$4.00","$92,000",-,12,17,2035,"$7,667"
Parking Garage,1.04,"Concrete repairs, B2 level","1",AL,"$40,000","$40,000",2011,20,13,2031,"$2,000"
Parking Garage,1.05,"Vehicle traffic coating B2 level, first time","18,000",SF,"$6.00","$108,000",-,one_time_project,6,2024,"$-"
Parking Garage,1.06,"Vehicle traffic coating, B2 level, recoat","18,000",SF,"$4.00","$72,000",-,12,18,2036,"$6,000"
Parking Garage,1.07,"Paint garage","1",LS,"$80,000","$80,000",-,20,6,2024,"$4,000"
Parking Garage,1.08,"Garage door replacement","2",EA,"$15,000","$30,000",-,15,5,2023,"$2,000"
Parking Garage,1.09,"Garage door repair allowance","1",AL,"$5,000","$5,000",-,5,10,2028,"$1,000"
Parking Garage,1.10,"Loading dock doors replacement","1",LS,"$15,000","$15,000",-,15,4,2022,"$1,000"
Parking Garage,1.11,"Garage railings","1",AL,"$5,000","$5,000",-,40,6,2024,"$125"
Parking Garage,1.12,"Garage exhaust fans","1",AL,"$5,000","$5,000",-,10,5,2023,"$500"
Parking Garage,1.13,"Wall leak repair allowance","1",AL,"$6,000","$6,000",-,10,1,2019,"$600"
Parking Garage,1.14,"Garage expansion joint seal","80",LF,"$200","$16,000",-,15,5,2023,"$1,067"
Parking Garage,1.15,"Garage steel beams and fireproofing","1",AL,"$10,000","$10,000",1972,55,6,2024,"$182"
Site Features,2.01,"Gate house exterior refurbish","1",AL,"$15,000","$15,000",-,20,6,2024,"$750"
Site Features,2.02,"Gate house interior refurbish","1",AL,"$15,000","$15,000",-,20,6,2024,"$750"
Site Features,2.03,"Board room building exterior repairs","1",AL,"$80,000","$80,000",-,20,4,2022,"$4,000"
Site Features,2.04,"Board room building interior refurbish","1",AL,"$50,000","$50,000",-,20,4,2022,"$2,500"
Site Features,2.05,"Water feature pump and filter","1",LS,"$5,000","$5,000",-,15,3,2021,"$333"
Site Features,2.06,"Water feature piping","1",AL,"$30,000","$30,000",1972,55,9,2027,"$545"
Site Features,2.07,"Upper basin wall and basin repairs","1",AL,"$7,500","$7,500",-,10,6,2024,"$750"
Site Features,2.08,"Upper basin coating","1,000",SF,"$5.00","$5,000",2014,10,6,2024,"$500"
Site Features,2.09,"Stone wall repairs","1",AL,"$25,000","$25,000",-,10,1,2019,"$2,500"
Site Features,2.10,"Reflecting pool basin repairs","1",AL,"$10,000","$10,000",-,10,6,2024,"$1,000"
Site Features,2.11,"Reflecting pool basin coating","10,000",SF,"$5.00","$50,000",2014,10,6,2024,"$5,000"
Site Features,2.12,"Tennis court fence","400",LF,"$50","$20,000",-,40,14,2032,"$500"
Site Features,2.13,"Tennis court nets and wind screens","1",LS,"$5,000","$5,000",-,15,10,2028,"$333"
Site Features,2.14,"Tennis court resurfacing","1",LS,"$35,000","$35,000",2013,15,10,2028,"$2,333"
Site Features,2.15,"Tennis court reconstruction","1",LS,"$150,000","$150,000",1972,60,14,2032,"$2,500"
Site Features,2.16,"Property perimeter fence","200",LF,"$50","$10,000",1972,55,9,2027,"$182"
Site Features,2.17,"Signage and site fixtures","1",AL,"$10,000","$10,000",-,20,6,2024,"$500"
Site Features,2.18,"Drainage improvement allowance","1",AL,"$25,000","$25,000",-,20,8,2026,"$1,250"
Site Features,2.19,"Tree maintenance and repair allowance","1",AL,"$30,000","$30,000",-,20,3,2021,"$1,500"
Site Features,2.20,"Landscape restoration allowance","1",AL,"$30,000","$30,000",-,20,4,2022,"$1,500"
Site Features,2.21,"Irrigation allowance","1",AL,"$15,000","$15,000",2012,15,9,2027,"$1,000"
Site Features,2.22,"Handrails","1",AL,"$10,000","$10,000",-,10,8,2026,"$1,000"
Site Features,2.23,"Sidewalk replacement","1",AL,"$25,000","$25,000",-,10,3,2021,"$2,500"
Site Features,2.24,"Front asphalt pavement sealing","2,600",SY,"$3.00","$7,800",2016,6,4,2022,"$1,300"
Site Features,2.25,"Service area asphalt pavement sealing","850",SY,"$3.00","$2,550",2016,6,4,2022,"$425"
Site Features,2.26,"Front asphalt milling and repaving","2,600",SY,"$25","$65,000",-,24,16,2034,"$2,708"
Site Features,2.27,"Service area asphalt milling and repaving","850",SY,"$25","$21,250",-,24,16,2034,"$885"
Site Features,2.28,"Curb and gutter replacement allowance","1",AL,"$25,000","$25,000",-,24,16,2034,"$1,042"
Site Features,2.29,"Trench drains","1",AL,"$25,000","$25,000",-,20,16,2034,"$1,250"
Site Features,2.30,"Site master plan","1",AL,"$5,000","$5,000",-,20,2,2020,"$250"
Site Features,2.31,"Stormwater system repair allowance","1",AL,"$40,000","$40,000",-,15,10,2028,"$2,667"
Site Features,2.32,"Storage shed","1",AL,"$20,000","$20,000",-,30,2,2020,"$667"
Pool Facilities,3.01,"Whitecoat pool","1",LS,"$10,000","$10,000",2018,8,8,2026,"$1,250"
Pool Facilities,3.02,"Tile and coping","150",LF,"$80","$12,000",2018,25,25,2043,"$480"
Pool Facilities,3.03,"Pool deck coating","3,000",SF,"$5.00","$15,000",2018,10,10,2028,"$1,500"
Pool Facilities,3.04,"Pool pump and filters","1",LS,"$5,000","$5,000",2018,15,15,2033,"$333"
Pool Facilities,3.05,"Pool piping","1",LS,"$30,000","$30,000",-,50,20,2038,"$600"
Pool Facilities,3.06,"Redecorate pool area","1",AL,"$10,000","$10,000",2018,12,12,2030,"$833"
Pool Facilities,3.07,"Pool heat exchanger","1",EA,"$10,000","$10,000",-,35,7,2025,"$286"
Pool Facilities,3.08,"Pool furniture allowance","1",AL,"$8,000","$8,000",2018,8,8,2026,"$1,000"
Pool Facilities,3.09,"Pool deck replacement","3,000",SF,"$25","$75,000",2018,30,20,2038,"$2,500"
Pool Facilities,3.10,"Pool fittings and fixtures","1",LS,"$20,000","$20,000",2018,30,20,2038,"$667"
Pool Facilities,3.11,"Pool doors and windows","1",LS,"$80,000","$80,000",1972,50,4,2022,"$1,600"
Pool Facilities,3.12,"Pool area lighting","1",LS,"$25,000","$25,000",2018,15,15,2033,"$1,667"
Roofing,4.01,"Gate house roof","1",LS,"$6,000","$6,000",1972,50,4,2022,"$120"
Roofing,4.02,"Board room building roof","3,000",SF,"$15","$45,000",2011,20,13,2031,"$2,250"
Roofing,4.03,"Main roof replacement","28,000",SF,"$35","$980,000",1990,35,7,2025,"$28,000"
Roofing,4.04,"Main roof repairs","1",AL,"$10,000","$10,000",-,10,17,2035,"$1,000"
Roofing,4.05,"Roof expansion joint","80",LF,"$70","$5,600",-,15,7,2025,"$373"
Roofing,4.06,"Cooling tower roof replacement","1,200",SF,"$40","$48,000",1990,25,7,2025,"$1,920"
Roofing,4.07,"Cooling tower roof repairs","1",AL,"$3,000","$3,000",-,10,1,2019,"$300"
Roofing,4.08,"West stairway roof replacement","1,200",SF,"$30","$36,000",1990,35,7,2025,"$1,029"
Roofing,4.09,"West stairway roof repairs","1",AL,"$2,000","$2,000",-,15,17,2035,"$133"
Roofing,4.10,"Roof fall protection","1",AL,"$20,000","$20,000",-,15,1,2019,"$1,333"
Roofing,4.11,"Roof anchors","1",LS,"$250,000","$250,000",-,35,7,2025,"$7,143"
Roofing,4.12,"Entrance canopy roof","1,000",SF,"$20","$20,000",-,20,12,2030,"$1,000"
Roofing,4.13,"Roof over pool area","1",LS,"$8,000","$8,000",1972,50,4,2022,"$160"
Roofing,4.14,"Waterfall equipment room roof","1",LS,"$10,000","$10,000",-,30,6,2024,"$333"
Building Exterior,5.01,"Exterior maintenance program","1",LS,"$600,000","$600,000",-,one_time_project,2,2020,"$-"
Building Exterior,5.02,"Replace exterior caulk","55,000",LF,"$7.00","$385,000",-,15,11,2029,"$25,667"
Building Exterior,5.03,"Clean exterior walls","1",LS,"$300,000","$300,000",-,15,11,2029,"$20,000"
Building Exterior,5.04,"Concrete repair allowance","1",AL,"$300,000","$300,000",-,15,11,2029,"$20,000"
Building Exterior,5.05,"Recoat balcony and terrace decks","65,000",SF,"$8.00","$520,000",-,15,11,2029,"$34,667"
Building Exterior,5.06,"Repair and paint balcony ceilings","65,000",SF,"$5.00","$325,000",-,15,11,2029,"$21,667"
Building Exterior,5.07,"Stucco repair allowance","1",AL,"$50,000","$50,000",-,15,11,2029,"$3,333"
Building Exterior,5.08,"Brick pointing allowance","1",AL,"$50,000","$50,000",-,15,11,2029,"$3,333"
Building Exterior,5.09,"Paint balcony railings","1",LS,"$400,000","$400,000",-,one_time_project,2,2020,"$-"
Building Exterior,5.10,"Replace balcony railings","5,500",LF,"$200","$1,100,000",1972,55,21,2039,"$20,000"
Building Exterior,5.11,"Replace residential windows and doors","47,000",SF,"$70","$3,290,000",1972,55,21,2039,"$59,818"
Building Exterior,5.12,"Replace curtainwall at elevator lobbies","2,800",SF,"$85","$238,000",1972,55,11,2029,"$4,327"
Building Exterior,5.13,"Replace other windows","600",SF,"$75","$45,000",1972,55,11,2029,"$818"
Building Exterior,5.14,"Replace main lobby doors and windows","1",LS,"$60,000","$60,000",1972,55,11,2029,"$1,091"
Building Exterior,5.15,"Stone walls at main entrance","1",AL,"$50,000","$50,000",-,20,7,2025,"$2,500"
Building Exterior,5.16,"Entrance canopy soffit","1",AL,"$20,000","$20,000",-,15,7,2025,"$1,333"
Building Exterior,5.17,"Terrace soffits","1",AL,"$30,000","$30,000",-,15,21,2039,"$2,000"
Building Exterior,5.18,"Paint exterior concrete","1",LS,"$50,000","$50,000",-,15,21,2039,"$3,333"
Building Exterior,5.19,"Post tensioned concrete repair allowance","1",AL,"$40,000","$40,000",-,15,21,2039,"$2,667"
Building Exterior,5.20,"Cooling tower screen walls","1",AL,"$20,000","$20,000",1972,40,6,2024,"$500"
Mechanical Systems,6.01,"Refurbish cooling towers","1",AL,"$65,000","$65,000",-,30,48,2066,"$2,167"
Mechanical Systems,6.02,"Replace cooling towers","2",EA,"$150,000","$300,000",2006,30,18,2036,"$10,000"
Mechanical Systems,6.03,"Refurbish chillers","1",AL,"$30,000","$30,000",-,30,36,2054,"$1,000"
Mechanical Systems,6.04,"Replace chillers","2",EA,"$250,000","$500,000",1994,30,6,2024,"$16,667"
Mechanical Systems,6.05,"Refurbish boilers","1",AL,"$30,000","$30,000",-,15,18,2036,"$2,000"
Mechanical Systems,6.06,"Replace boilers","2",EA,"$550,000","$1,100,000",1972,30,3,2021,"$36,667"
Mechanical Systems,6.07,"Heat exchanger 1 - basement areas","1",EA,"$35,000","$35,000",1972,30,4,2022,"$1,167"
Mechanical Systems,6.08,"Heat exchanger 2 - residential FCUs","1",EA,"$50,000","$50,000",1972,30,5,2023,"$1,667"
Mechanical Systems,6.09,"Heat exchanger 3 - domestic hot water","0",EA,"$35,000","$35,000",1972,-,-,-,"$-"
Mechanical Systems,6.10,"Heat exchanger 4 - swimming pool","1",EA,"$30,000","$30,000",1972,30,7,2025,"$1,000"
Mechanical Systems,6.11,"Steam condensate tank","1",EA,"$40,000","$40,000",2016,40,38,2056,"$1,000"
Mechanical Systems,6.12,"Chilled water pumps","2",EA,"$15,000","$30,000",-,30,2,2020,"$1,000"
Mechanical Systems,6.13,"Condenser water pumps","2",EA,"$15,000","$30,000",-,30,4,2022,"$1,000"
Mechanical Systems,6.14,"Heating hot water pumps","2",EA,"$15,000","$30,000",-,30,6,2024,"$1,000"
Mechanical Systems,6.15,"Heating hot water loop pumps","2",EA,"$8,000","$16,000",-,30,8,2026,"$533"
Mechanical Systems,6.16,"HVAC control system","1",LS,"$40,000","$40,000",-,30,10,2028,"$1,333"
Mechanical Systems,6.17,"AHU-1 - west hallways and residences","1",EA,"$100,000","$100,000",2008,30,20,2038,"$3,333"
Mechanical Systems,6.18,"AHU-2 - east hallways and residences","1",EA,"$100,000","$100,000",2008,30,20,2038,"$3,333"
Mechanical Systems,6.19,"AHU-3 - B3 level","1",EA,"$50,000","$50,000",2007,30,19,2037,"$1,667"
Mechanical Systems,6.20,"AHU-4 - swimming pool","1",EA,"$75,000","$75,000",2007,30,19,2037,"$2,500"
Mechanical Systems,6.21,"Steam injection humidifiers","2",EA,"$8,000","$16,000",2000,25,7,2025,"$640"
Mechanical Systems,6.22,"Roof level exhaust fans","1",LS,"$360,000","$360,000",-,30,1,2019,"$12,000"
Mechanical Systems,6.23,"Mechanical room exhaust fans","1",AL,"$5,000","$5,000",-,10,4,2022,"$500"
Mechanical Systems,6.24,"Valve replacement allowance","1",AL,"$20,000","$20,000",-,5,2,2020,"$4,000"
Mechanical Systems,6.25,"East system water piping","1",LS,"$800,000","$800,000",1972,55,9,2027,"$14,545"
Mechanical Systems,6.26,"West system water piping","1",LS,"$700,000","$700,000",1972,55,9,2027,"$12,727"
Mechanical Systems,6.27,"Condenser water piping","1",LS,"$60,000","$60,000",1972,60,14,2032,"$1,000"
Mechanical Systems,6.28,"Boiler room piping and valves","1",LS,"$100,000","$100,000",1972,65,19,2037,"$1,538"
Mechanical Systems,6.29,"Boiler breeching","1",LS,"$40,000","$40,000",1972,45,3,2021,"$889"
Mechanical Systems,6.30,"Boiler flue","1",AL,"$50,000","$50,000",1972,50,5,2023,"$1,000"
Mechanical Systems,6.31,"Boiler room ventilation fan","1",EA,"$25,000","$25,000",-,35,11,2029,"$714"
Mechanical Systems,6.32,"Residential fan coil units","549",EA,"$5,000","$2,745,000",2014,30,26,2044,"$91,500"
Mechanical Systems,6.33,"Common area fan coil units","18",EA,"$5,000","$90,000",2015,30,27,2045,"$3,000"
Mechanical Systems,6.34,"AHU & pipe modifications for new system","1",LS,"$50,000","$50,000",-,one_time_project,3,2021,"$-"
Mechanical Systems,6.35,"Fuel oil tank","1",EA,"$60,000","$60,000",-,40,12,2030,"$1,500"
Mechanical Systems,6.36,"Fuel oil transfer pumps and piping","1",LS,"$25,000","$25,000",-,30,10,2028,"$833"
Mechanical Systems,6.37,"Indoor air ducts","1",AL,"$150,000","$150,000",1972,65,19,2037,"$2,308"
Mechanical Systems,6.38,"Air balancing","1",AL,"$10,000","$10,000",-,10,2,2020,"$1,000"
Mechanical Systems,6.39,"Board room building HVAC","1",LS,"$25,000","$25,000",2000,25,7,2025,"$1,000"
Mechanical Systems,6.40,"Elevator machine room HVAC","2",EA,"$20,000","$40,000",2009,20,11,2029,"$2,000"
Electrical Systems,7.01,"High voltage switchgear","1",LS,"$550,000","$550,000",1972,60,14,2032,"$9,167"
Electrical Systems,7.02,"Dry transformers","1",LS,"$50,000","$50,000",1972,60,14,2032,"$833"
Electrical Systems,7.03,"Common element load centers","1",LS,"$250,000","$250,000",1972,60,14,2032,"$4,167"
Electrical Systems,7.04,"EV charging station equipment","1",LS,"$30,000","$30,000",2018,30,30,2048,"$1,000"
Electrical Systems,7.05,"Common element wiring","1",LS,"$250,000","$250,000",1972,65,19,2037,"$3,846"
Electrical Systems,7.06,"Emergency generator","1",EA,"$120,000","$120,000",2009,30,21,2039,"$4,000"
Electrical Systems,7.07,"Transfer switches","1",LS,"$35,000","$35,000",2009,30,21,2039,"$1,167"
Electrical Systems,7.08,"Interior lighting","1",AL,"$25,000","$25,000",-,30,12,2030,"$833"
Electrical Systems,7.09,"Garage lighting","1",AL,"$15,000","$15,000",-,30,10,2028,"$500"
Electrical Systems,7.10,"Exterior lighting","1",AL,"$25,000","$25,000",-,20,8,2026,"$1,250"
Electrical Systems,7.11,"Electric system preventive maintenance","1",AL,"$10,000","$10,000",-,3,2,2020,"$3,333"
Electrical Systems,7.12,"Electric unit heaters","1",AL,"$5,000","$5,000",-,10,8,2026,"$500"
Plumbing Systems,8.01,"Domestic water booster pumps","1",LS,"$40,000","$40,000",2007,25,14,2032,"$1,600"
Plumbing Systems,8.02,"Domestic water circulating pump","1",EA,"$5,000","$5,000",-,15,8,2026,"$333"
Plumbing Systems,8.03,"Domestic water pressure tank","1",EA,"$15,000","$15,000",2007,35,24,2042,"$429"
Plumbing Systems,8.04,"Domestic hot water boilers & tank","1",LS,"$180,000","$180,000",-,30,3,2021,"$6,000"
Plumbing Systems,8.05,"Water main","1",EA,"$40,000","$40,000",1972,65,19,2037,"$615"
Plumbing Systems,8.06,"Domestic water distribution pipes","1",LS,"$1,200,000","$1,200,000",1972,55,9,2027,"$21,818"
Plumbing Systems,8.07,"Sanitary drain pipe risers","1",LS,"$1,200,000","$1,200,000",1972,60,14,2032,"$20,000"
Plumbing Systems,8.08,"Storm water drain risers","1",LS,"$200,000","$200,000",1972,60,14,2032,"$3,333"
Plumbing Systems,8.09,"Storm and sanitary drain main pipes","1",AL,"$50,000","$50,000",1972,10,6,2024,"$5,000"
Plumbing Systems,8.10,"Condensate drain pipes","1",LS,"$600,000","$600,000",1972,55,9,2027,"$10,909"
Plumbing Systems,8.11,"Dry valves for garage sprinklers","1",LS,"$30,000","$30,000",2017,15,14,2032,"$2,000"
Plumbing Systems,8.12,"Garage sprinkler pipes","1",LS,"$150,000","$150,000",1972,55,9,2027,"$2,727"
Plumbing Systems,8.13,"Gas pipe system","1",AL,"$50,000","$50,000",1972,70,24,2042,"$714"
Miscellaneous Equipment,9.01,"Elevator hoisting equipment and controls","6",EA,"$180,000","$1,080,000",2009,40,31,2049,"$27,000"
Miscellaneous Equipment,9.02,"Elevator door equipment","6",EA,"$35,000","$210,000",2009,20,11,2029,"$10,500"
Miscellaneous Equipment,9.03,"Elevator cab redecoration allowance","6",EA,"$15,000","$90,000",2009,20,11,2029,"$4,500"
Miscellaneous Equipment,9.04,"Fire alarm control panels","1",AL,"$40,000","$40,000",2017,20,19,2037,"$2,000"
Miscellaneous Equipment,9.05,"Fire alarm system renovation","1",AL,"$500,000","$500,000",2017,40,39,2057,"$12,500"
Miscellaneous Equipment,9.06,"Surveillance equipment","1",AL,"$30,000","$30,000",-,15,5,2023,"$2,000"
Miscellaneous Equipment,9.07,"Trash compactors","2",EA,"$25,000","$50,000",1991,30,3,2021,"$1,667"
Miscellaneous Equipment,9.08,"Entry access systems","1",LS,"$40,000","$40,000",-,30,8,2026,"$1,333"
Miscellaneous Equipment,9.09,"Trash chutes","2",EA,"$40,000","$80,000",-,30,8,2026,"$2,667"
Interior Finishes and Furnishing,10.01,"Hallway redecoration","1",AL,"$500,000","$500,000",2018,15,15,2033,"$33,333"
Interior Finishes and Furnishing,10.02,"Elevator lobby redecoration","1",AL,"$100,000","$100,000",2018,15,15,2033,"$6,667"
Interior Finishes and Furnishing,10.03,"Painting allowance","1",AL,"$60,000","$60,000",2018,7,7,2025,"$8,571"
Interior Finishes and Furnishing,10.04,"Common area furnishing allowance","1",AL,"$60,000","$60,000",2018,15,15,2033,"$4,000"
Interior Finishes and Furnishing,10.05,"Unit entry doors","1",AL,"$250,000","$250,000",-,50,32,2050,"$5,000"
Interior Finishes and Furnishing,10.06,"Lobby renovation","1",AL,"$120,000","$120,000",2018,20,20,2038,"$6,000"
Interior Finishes and Furnishing,10.07,"Management office redecoration","1",AL,"$30,000","$30,000",-,20,4,2022,"$1,500"
Interior Finishes and Furnishing,10.08,"Service hallway redecoration","1",AL,"$60,000","$60,000",-,15,10,2028,"$4,000"
Interior Finishes and Furnishing,10.09,"Locker and bath room renovation","1",AL,"$80,000","$80,000",2018,20,20,2038,"$4,000"
Interior Finishes and Furnishing,10.10,"Sauna renovation","1",AL,"$30,000","$30,000",2018,15,15,2033,"$2,000"
Interior Finishes and Furnishing,10.11,"Fitness center equipment replacement","1",AL,"$15,000","$15,000",2018,7,7,2025,"$2,143"
Interior Finishes and Furnishing,10.12,"Fitness center redecoration","1",AL,"$30,000","$30,000",2018,15,15,2033,"$2,000"
Interior Finishes and Furnishing,10.13,"Office equipment","1",AL,"$5,000","$5,000",-,5,1,2019,"$1,000"
Interior Finishes and Furnishing,10.14,"Mailboxes","1",LS,"$50,000","$50,000",-,40,10,2028,"$1,250"

In [1]:
import pandas as pd

In [39]:

df=pd.read_csv("ADORBinput.csv")
df.head()

,Component Category,Item Number,Component Name,Freq,Cost,Embo Calc,L1 LaborFrac,L1 CountryofOrigin,L2 Subcategory,L2 Emissions Intensity,L2 Emissions Intensity unit,L2 Quantity,L2 docs,L2pers IncomeFrac,L2pers CO2eTons,L2pers %better
0,Embodied Carbon,11.01,Substitute mass timber for steel,one_time_project,NaN,L2mat,NaN,NaN,Material,0.2,kgCO2e/kg,3000.0,NaN,NaN,NaN,NaN
1,Embodied Carbon,11.02,Domestic window supplier (no ocean shipping),55,NaN,L2biz,NaN,NaN,Biz Process,0.0,kg/ton.km,0.0,NaN,NaN,NaN,NaN
2,Embodied Carbon,11.03,GSW,one_time_project,NaN,L2pers,NaN,NaN,Personal,NaN,NaN,NaN,NaN,0.125,20.0,36%
3,Parking Garage,1.01,"Concrete repairs, B1 level",12,"$50,000",L1,50%,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Parking Garage,1.02,"Vehicle traffic coating B1 level, first time",one_time_project,"$138,000",L1,50%,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
NE=pd.read_csv("NatlEmission.csv")
NE.head()

   Country GDP [USD millions]  CO2 [Megatons]  Emission intens [kg/$]
0      USA      20,936,600.00          4900.0                   0.234
1   Canada       1,643,407.98           565.2                   0.344
2    China      14,722,730.70          9500.0                   0.645
3   France       2,603,004.40           303.5                   0.117
4  Germany       3,806,060.14           696.1                   0.183

In [41]:

#df.index
#df.columns

#print(df["Component Category"])
#print(df[df["Component Category"]=="Embodied Carbon"])

#tmp=df["Component Name"]
#tmp.head()

df1=df
df1["Freq"]=df1["Freq"].str.replace("one_time_project","9999")
df1["Freq"]=pd.to_numeric(df1["Freq"],errors="coerce")
df1["Cost"]=df1["Cost"].str.replace("^\$","",regex=True)
df1["Cost"]=df1["Cost"].str.replace(",","")
df1["Cost"]=pd.to_numeric(df1["Cost"],errors="coerce")
df1["L1 LaborFrac"]=df1["L1 LaborFrac"].str.replace("%","")
df1["L1 LaborFrac"]=pd.to_numeric(df1["L1 LaborFrac"],errors="coerce")
df1["L2pers %better"]=df1["L2pers %better"].str.replace("%","")
df1.head()
#df1.info()

,Component Category,Item Number,Component Name,Freq,Cost,Embo Calc,L1 LaborFrac,L1 CountryofOrigin,L2 Subcategory,L2 Emissions Intensity,L2 Emissions Intensity unit,L2 Quantity,L2 docs,L2pers IncomeFrac,L2pers CO2eTons,L2pers %better
0,Embodied Carbon,11.01,Substitute mass timber for steel,9999.0,NaN,L2mat,NaN,NaN,Material,0.2,kgCO2e/kg,3000.0,NaN,NaN,NaN,NaN
1,Embodied Carbon,11.02,Domestic window supplier (no ocean shipping),55.0,NaN,L2biz,NaN,NaN,Biz Process,0.0,kg/ton.km,0.0,NaN,NaN,NaN,NaN
2,Embodied Carbon,11.03,GSW,9999.0,NaN,L2pers,NaN,NaN,Personal,NaN,NaN,NaN,NaN,0.125,20.0,36
3,Parking Garage,1.01,"Concrete repairs, B1 level",12.0,50000.0,L1,50.0,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Parking Garage,1.02,"Vehicle traffic coating B1 level, first time",9999.0,138000.0,L1,50.0,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
tmp=pd.merge(left=df1,right=NE,how="left",on=None,left_on="L1 CountryofOrigin",right_on="Country",sort=False,validate="many_to_one")
del tmp["GDP [USD millions]"] #Intro to data structures -> column selection, addition, deletion
del tmp["CO2 [Megatons]"]
del tmp["Country"]
df2=tmp.rename(
    columns={"Emission intens [kg/$]":"L1 Matl Em Intens"}
)

dfL1=df2[df2["Embo Calc"].str.contains("L1")] #rows where Embo Calc contains L1
dfL2=df2[df2["Embo Calc"].str.contains("L2")] #rows where Embo Calc contains L2 

dfL1.head()

,Component Category,Item Number,Component Name,Freq,Cost,Embo Calc,L1 LaborFrac,L1 CountryofOrigin,L2 Subcategory,L2 Emissions Intensity,L2 Emissions Intensity unit,L2 Quantity,L2 docs,L2pers IncomeFrac,L2pers CO2eTons,L2pers %better,L1 Matl Em Intens
3,Parking Garage,1.01,"Concrete repairs, B1 level",12.0,50000.0,L1,50.0,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.645
4,Parking Garage,1.02,"Vehicle traffic coating B1 level, first time",9999.0,138000.0,L1,50.0,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.645
5,Parking Garage,1.03,"Vehicle traffic coating, B1 level, recoat",12.0,92000.0,L1,50.0,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.645
6,Parking Garage,1.04,"Concrete repairs, B2 level",20.0,40000.0,L1,50.0,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.645
7,Parking Garage,1.05,"Vehicle traffic coating B2 level, first time",9999.0,108000.0,L1,50.0,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.645

In [43]:
dfL1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 181 entries, 3 to 183
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Component Category           181 non-null    object
 1   Item Number                  181 non-null    float64
 2   Component Name               181 non-null    object
 3   Freq                         180 non-null    float64
 4   Cost                         181 non-null    float64
 5   Embo Calc                    181 non-null    object
 6   L1 LaborFrac                 181 non-null    float64
 7   L1 CountryofOrigin           181 non-null    object
 8   L2 Subcategory               0 non-null      object
 9   L2 Emissions Intensity       0 non-null      float64
 10  L2 Emissions Intensity unit  0 non-null      object
 11  L2 Quantity                  0 non-null      float64
 12  L2 docs                      0 non-null      float64
 13  L2pers IncomeFrac            0 non-null      float64
 14  L2pers CO2eTons              0 non-null      float64
 15  L2pers %better               0 non-null      object
 16  L1 Matl Em Intens            181 non-null    float64
dtypes: float64(10), object(7)
memory usage: 25.5+ KB

In [44]:
dfL2.head()

,Component Category,Item Number,Component Name,Freq,Cost,Embo Calc,L1 LaborFrac,L1 CountryofOrigin,L2 Subcategory,L2 Emissions Intensity,L2 Emissions Intensity unit,L2 Quantity,L2 docs,L2pers IncomeFrac,L2pers CO2eTons,L2pers %better,L1 Matl Em Intens
0,Embodied Carbon,11.01,Substitute mass timber for steel,9999.0,NaN,L2mat,NaN,NaN,Material,0.2,kgCO2e/kg,3000.0,NaN,NaN,NaN,NaN,NaN
1,Embodied Carbon,11.02,Domestic window supplier (no ocean shipping),55.0,NaN,L2biz,NaN,NaN,Biz Process,0.0,kg/ton.km,0.0,NaN,NaN,NaN,NaN,NaN
2,Embodied Carbon,11.03,GSW,9999.0,NaN,L2pers,NaN,NaN,Personal,NaN,NaN,NaN,NaN,0.125,20.0,36,NaN

In [45]:
dfL2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3 entries, 0 to 2
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Component Category           3 non-null      object
 1   Item Number                  3 non-null      float64
 2   Component Name               3 non-null      object
 3   Freq                         3 non-null      float64
 4   Cost                         0 non-null      float64
 5   Embo Calc                    3 non-null      object
 6   L1 LaborFrac                 0 non-null      float64
 7   L1 CountryofOrigin           0 non-null      object
 8   L2 Subcategory               3 non-null      object
 9   L2 Emissions Intensity       2 non-null      float64
 10  L2 Emissions Intensity unit  2 non-null      object
 11  L2 Quantity                  2 non-null      float64
 12  L2 docs                      0 non-null      float64
 13  L2pers IncomeFrac            1 non-null      float64
 14  L2pers CO2eTons              1 non-null      float64
 15  L2pers %better               1 non-null      object
 16  L1 Matl Em Intens            0 non-null      float64
dtypes: float64(10), object(7)
memory usage: 432.0+ bytes

In [ ]:
class Societal(): # Societal parameters
    def __init__(self):
        self.GridDecarbDate = None
        self.DiscountDirectEnrg = None
        self.EmissionFactorElec = None
        self.CarbonCost = None
        self.DiscountOpCarbon = None
        self.DiscountDirectMaint = None
        self.EmissionIntensLabor = None
        self.DiscountEmCarbon = None
        self.NewNameplateGridCap = None
        self.NatlGridTransCost = None
        self.DiscountTransCost = None

class OpPwrNrg(): # Operating annual energy & peak electric power for the post-construction configuration
    def __init__(self):
        self.GasPost = None #Gas usage, Therms per year
        self.ElecPost = None #Electrical usage, kWh per year
        self.PeakElec = None #Peak hour electrical power, kW
        
Forever = 9999 #years
def ADORB1(StartYear, PhaseYears, Societal, OpPwrNrg, ProjItems):
    # StartYear - year of construction, of deployment of a phase of a retrofit project
    # PhaseYears - Analysis period, number of years the building stays in a configuration (including maintenance)
    # Societal
    # OpPwrNrg
    # ProjItems - 

    EmboSubcats = {"Material","Biz Process","Personal"}
    Countries = {"USA","Canada","China","France","Germany","India","Ireland","Italy","Japan","Korea","Malaysia","Mexico","Switzerland","Taiwan","United Kingdom","Vietnam"}